let trinkets = [
    "A mummified goblin hand",
    "A piece of crystal that faintly glows in the moonlight",
    "A gold coin minted in an unknown land",
    "A diary written in a language you don't know",
    "A brass ring that never tarnishes",
    "An old chess piece made from glass",
    "A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips",
    "A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it",
    "A rope necklace from which dangles four mummified elf fingers",
    "The deed for a parcel of land in a realm unknown to you",
    "A 1-ounce block made from an unknown material",
    "A small cloth doll skewered with needles",
    "A tooth from an unknown beast",
    "An enormous scale, perhaps from a dragon",
    "A bright green feather",
    "An old divination card bearing your likeness",
    "A glass orb filled with moving smoke",
    "A 1-pound egg with a bright red shell",
    "A pipe that blows bubbles",
    "A glass jar containing a weird bit of flesh floating in pickling fluid",
    "A tiny gnome-crafted music box that plays a song you dimly remember from your childhood",
    "A small wooden statuette of a smug halfling",
    "A brass orb etched with strange runes",
    "A multicolored stone disk",
    "A tiny silver icon of a raven",
    "A bag containing forty-seven humanoid teeth, one of which is rotten",
    "A shard of obsidian that always feels warm to the touch",
    "A dragon's bony talon hanging from a plain leather necklace",
    "A pair of old socks",
    "A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking",
    "A silver badge in the shape of a five-pointed star",
    "A knife that belonged to a relative",
    "A glass vial filled with nail clippings",
    "A rectangular metal device with two tiny metal cups on one end that throws sparks when wet",
    "A white, sequined glove sized for a human",
    "A vest with one hundred tiny pockets",
    "A small, weightless stone block",
    "A tiny sketch portrait of a goblin",
    "An empty glass vial that smells of perfume when opened",
    "A gemstone that looks like a lump of coal when examined by anyone but you",
    "A scrap of cloth from an old banner",
    "A rank insignia from a lost legionnaire",
    "A tiny silver bell without a clapper",
    "A mechanical canary inside a gnomish lamp",
    "A tiny chest carved to look like it has numerous feet on the bottom",
    "A dead sprite inside a clear glass bottle",
    "A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)",
    "A glass orb filled with water, in which swims a clockwork goldfish",
    "A silver spoon with an 'M' engraved on the handle",
    "A whistle made from gold-colored wood",
    "A dead scarab beetle the size of your hand",
    "Two toy soldiers, one with a missing head",
    "A small box filled with different-sized buttons",
    "A candle that can't be lit",
    "A tiny cage with no door",
    "An old key",
    "An indecipherable treasure map",
    "A hilt from a broken sword",
    "A rabbit's foot",
    "A glass eye",
    "A cameo carved in the likeness of a hideous person",
    "A silver skull the size of a coin",
    "An alabaster mask",
    "A pyramid of sticky black incense that smells very bad",
    "A nightcap that, when worn, gives you pleasant dreams",
    "A single caltrop made from bone",
    "A gold monocle frame without the lens",
    "A 1-inch cube, each side painted a different color",
    "A crystal knob from a door",
    "A small packet filled with pink dust",
    "A fragment of a beautiful song, written as musical notes on two pieces of parchment",
    "A silver teardrop earring made from a real teardrop",
    "The shell of an egg painted with scenes of human misery in disturbing detail",
    "A fan that, when unfolded, shows a sleeping cat",
    "A set of bone pipes",
    "A four-leaf clover pressed inside a book discussing manners and etiquette",
    "A sheet of parchment upon which is drawn a complex mechanical contraption",
    "An ornate scabbard that fits no blade you have found so far",
    "An invitation to a party where a murder happened",
    "A bronze pentacle with an etching of a rat's head in its center",
    "A purple handkerchief embroidered with the name of a powerful archmage",
    "Half of a floorplan for a temple, castle, or some other structure",
    "A bit of folded cloth that, when unfolded, turns into a stylish cap",
    "A receipt of deposit at a bank in a far-flung city",
    "A diary with seven missing pages",
    "An empty silver snuffbox bearing an inscription on the surface that says 'dreams'",
    "An iron holy symbol devoted to an unknown god",
    "A book that tells the story of a legendary hero's rise and fall, with the last chapter missing",
    "A vial of dragon blood",
    "An ancient arrow of elven design",
    "A needle that never bends",
    "An ornate brooch of dwarven design",
    "An empty wine bottle bearing a pretty label that says, 'The Wizard of Wines Winery, Red Dragon Crush, 331422-W'",
    "A mosaic tile with a multicolored, glazed surface",
    "A petrified mouse",
    "A black pirate flag adorned with a dragon's skull and crossbones",
    "A tiny mechanical crab or spider that moves about when it's not being observed",
    "A glass jar containing lard with a label that reads, 'Griffon Grease'",
    "A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body",
    "A metal urn containing the ashes of a hero",
    
    
    
    "A perfect skipping stone",
    "Three weighted dice that always roll low",
    "A locket with a picture of Jim Darkmagic",
    "A tiny anvil and smith's hammer",
    "A nonfunctional immovable rod",
    "A DIY acupuncture kit",
    "A stuffed owlbear toy",
    "A diagram for a new war lute",
    "A declaration of war against a nation no one has ever heard of",
    "A pipe that emits green smoke",
    "A glass eye",
    "The centerpiece of a priceless chandelier",
    "A fine cane with a secret compartment",
    "A letter written by Rosie Beestinger",
    "A coin that always lands on its edge",
    "The deed and title to an abandoned windmill and three acres of tillable land that you've never been able to find",
    "A menu from Big Daddy Donaar's Yum Yum Hut",
    "A small purse that screams loudly when opened",
    "A deep-crow-feather quill",
    "A pair of breeches that always smells faintly of honey",
    "A one-armed Viari doll (Apocalypse Dagger accessory missing)",
    "A leather pouch filled with various finger bones of unknown provenance",
    "The collar of your childhood pet, Nutmeg",
    "A seashell that, when pressed to the ear, speaks in flowing rhymes",
    "A recipe book for cooking with mushrooms",
    "One expired coupon for 'A Free Cornerstone'",
    "A portable beehive",
    "Goggles that literally tint everything rose colored",
    "A wand of wonder that allows you to cast only mending",
    "A bracelet woven from mistletoe",
    "A curved claw from an unknown beast that small children are always frightened of",
    "A longsword that can be folded down in 1 minute and hidden in your pocket",
    "A living graft of what you believe to be the World Tree",
    "A tattered scarf with the Acquisitions Incorporated logo",
    "A box containing a torn-up letter",
    "An old contract marked 'Void'",
    "A small pigeon in a cage",
    "An Acquisitions Incorporated 'Green Flame' foam finger",
    "A 'C' Team lunchbox",
    "A potted plant that grows different fruit on every branch",
    "A book of adventures for children",
    "An Omin action figure with detachable maul and holy symbol",
    "A pint glass engraved with a picture of a keg robot",
    "A giant hockey puck",
    "A miniature cannon that actually fires",
    "A very fancy red scarf and matching handkerchief",
    "An arrow once shot by Môrgæn",
    "A purple worm toy",
    "A burned doll whose eyes follow you around the room",
    "An infinite inkwell",
    "A band embroidered with the symbol of the Six",
    "A squishy cactus",
    "A velvet blindfold",
    "A dirty figurine of a triceratops that can't be cleaned",
    "A used (and thus nonmagical) noble knife from the Noble Knife",
    "A quill that rotates through all the colors of the rainbow",
    "A twenty-sided die that only rolls the number 4",
    "A pointed hat that glows in the dark",
    "A cup that hums when filled with water",
    "A mug fashioned from the skull of someone else's enemy",
    "A small glass jar containing an immortal firefly",
    "A fake mustache made from gnome facial hair",
    "A petrified troll finger",
    "Half of a map",
    "The other half of a map",
    "An unreasonable amount of pocket lint",
    "A dozen flyers for a local gnome food place",
    "Omin Dran's business card",
    "A lock of hair from a changeling",
    "A marble that rolls uphill",
    "A piece of parchment listing a command word for a powerful magic item",
    "A book titled Conversational Giant",
    "A user's manual for an apparatus of Kwalish",
    "A signed headshot of famous bard Spice Caraway",
    "The eye of a basilisk in a crystal box",
    "A postcard from Ravnica",
    "A stamp collection",
    "A small piece of solidified smoke",
    "A six-sided die that sometimes rolls a seven",
    "A left-hand gauntlet",
    "A music box that plays nursery rhymes",
    "A locket that's bigger on the outside than the inside",
    "A potted plant that grows hair instead of leaves",
    "A collection of teeth",
    "A coin whose minting date always shows three years in the future",
    "A green drinking horn taken from a very large bull",
    "A small book containing pressed and dried botanical samples",
    "A hatched chimera egg",
    "A slightly used red bandit mask",
    "A tiny stirge encased in amber",
    "A large bottle of Red Larch Ale that can't be opened",
    "A cane topped with a stylized golden bulldog",
    "A note in your own hand that you don't remember writing",
    "A sprig of herbs from your family's garden",
    "A tankard stolen from the Dran & Courtier",
    "A small, severed tentacle preserved in alcohol",
    "A walnut with a face drawn on it",
    "A small flask of liquid from the Lake of Radiant Mists",
    "An ice cube that never melts",
    "An expertly carved sword hilt with the blade snapped cleanly off",
    
    
    
    "A picture you drew as a child of your imaginary friend",
    "A lock that opens when blood is dripped in its keyhole",
    "Clothes stolen from a scarecrow",
    "A spinning top carved with four faces: happy, sad, wrathful, and dead",
    "The necklace of a sibling who died on the day you were born",
    "A wig from someone executed by beheading",
    "The unopened letter to you from your dying father",
    "A pocket watch that runs backward for an hour every midnight",
    "A winter coat stolen from a dying soldier",
    "A bottle of invisible ink that can only be read at sunset",
    "A wineskin that refills when interred with a dead person for a night",
    "A set of silverware used by a king for his last meal",
    "A spyglass that always shows the world suffering a terrible storm",
    "A cameo with the profile's face scratched away",
    "A lantern with a black candle that never runs out and that burns with green flame",
    "A teacup from a child's tea set, stained with blood",
    "A little black book that records your dreams, and yours alone, when you sleep",
    "A necklace formed of the interlinked holy symbols of a dozen deities",
    "A hangman's noose that feels heavier than it should",
    "A birdcage into which small birds fly but once inside never eat or leave",
    "A lepidopterist's box filled dead moths with skulllike patterns on their wings",
    "A jar of pickled ghouls' tongues",
    "The wooden hand of a notorious pirate",
    "An urn with the ashes of a dead relative",
    "A hand mirror backed with a bronze depiction of a medusa",
    "Pallid leather gloves crafted with ivory fingernails",
    "Dice made from the knuckles of a notorious charlatan",
    "A ring of keys for forgotten locks",
    "Nails from the coffin of a murderer",
    "A key to the family crypt",
    "A bouquet of funerary flowers that always looks and smells fresh",
    "A switch used to discipline you as a child",
    "A music box that plays by itself whenever someone holding it dances",
    "A walking cane with an iron ferrule that strikes sparks on stone",
    "A flag from a ship lost at sea",
    "Porcelain doll's head that always seems to be looking at you",
    "A wolf's head wrought in silver that is also a whistle",
    "A small mirror that shows a much older version of the viewer",
    "Small, worn book of children's nursery rhymes",
    "A mummified raven claw",
    "A broken pendent of a silver dragon that's always cold to the touch",
    "A small locked box that quietly hums a lovely melody at night but you always forget it in the morning",
    "An inkwell that makes one a little nauseous when staring at it",
    "An old little doll made from a dark, dense wood and missing a hand and a foot",
    "A black executioner's hood",
    "A pouch made of flesh, with a sinew drawstring",
    "A tiny spool of black thread that never runs out",
    "A tiny clockwork figurine of a dancer that's missing a gear and doesn't work",
    "A black wooden pipe that creates puffs of smoke that look like skulls",
    "A vial of perfume, the scent of which only certain creatures can detect",
    
    
    "A compass that always points to Mulmaster",
    "A paper fan that won't produce a breeze no matter how hard it's waved",
    "A petrified potato that resembles someone important to you",
    "A glass cup that can only be filled half way no matter how much liquid is poured into it",
    "A mirror that only shows the back of your head",
    "A small glass bird that when set down near water dips its head in as if to get a drink",
    "A lady's coin purse containing two sharp fangs",
    "A small sea conch with the words 'From the beginning' painted on the lip",
    "A frost-covered silver locket that's frozen shut",
    "A seal which imprints a mysterious, unknown coat of arms into hard rock",
    "A small wooden doll that when held brings back fond memories",
    "A small handmirror which only reflects inanimate objects",
    "A glass eyeball that looks about of its own accordance, and can roll around",
    "A glass orb that replicates yesterday's weather inside itself",
    "A drinking cup, that randomly fills with fresh or salt water. Refilling once emptied",
    "A deep blue piece of flint, that when struck with steel produces not a spark but a drop of water",
    "A conch shell which is always damp and constantly drips saltwater",
    "A charred, half-melted pewter clasp that glows as if smoldering but releases no heat",
    "A clockwork finch that flaps its wings in the presence of a breeze",
    "An unbreakable sealed jar of glowing water that hums when shaken",
    "A small, finely polished geode whose crystals slowly fade between every color of the spectrum",
    "A rough stone eye pulled from a petrified creature",
    "A stone smoking pipe that never needs lighting",
    "A small whistle, that when blown, whispers a name of a person or place unknown to you, instead of the whistle sound",
    "A fist sized rock that 'beats' like a heart",
    "A pair of bronze scissors in the shape of a pair of leaping dolphins",
    "A bronze oil lamp which is rumored to have once held a genie",
    "A single gauntlet inscribed with a fire motif and an unfamiliar name in Primordial",
    "A one-eyed little fish inside a spherical vial, much bigger than the vial's neck, He has a cunning look",
    "The tiny skull of a rabbit that whispers scathing insults when nobody is looking",
    "A rag doll in the likeness of an owlbear",
    "The desiccated body of a small eight-legged black lizard",
    "A small toy boat made with a walnut shell, toothpick, and piece of cloth",
    "A small pocket mirror that slowly fogs over while held",
    "Wind chimes that glow when the wind blows",
    "A small, clay square with an unknown rune etched into one side",
    "A tea kettle that heats itself when filled with water",
    "An old scratched monocle which shows an underwater landscape whenever someone looks through it",
    "A rose carved from coral",
    "A set of dice with elemental symbols and primordial runes instead of pips or numbers",
    "An amulet filled with liquid that churns, freezes, or boils to match it's wearer's mood",
    "A small silver bell that makes a sound like quiet, distant thunder when it's struck",
    "A small vial of black sand that glows slightly in the moonlight",
    "A small whale tooth with etched with an image of waves crashing upon a beach",
    "An hourglass in which the sands pour upward instead of downward",
    "A glass pendant with a hole in the center that a mild breeze always blows out of",
    "A soft feather that falls like a stone when dropped",
    "A large transparent gem that, when gripped tightly, whispers in Terran",
    "A small crystal snowglobe that, when shaken, seems to form silhouettes of dancing forms",
    "Half of a palm-sized geode that pulses dimly with purple light",
    "A book filled with writing that only appears when the book is held underwater",
    "A sealed envelope made of red leather that you haven't been able to open. It smells of campfire",
    "A locket of hair that is rumored to have come from a famed fire genasi",
    "Flint and steel that, when used to start a fire, creates a random colored flame",
    "A blank piece of wet parchment that never seems to dry",
    "A small puzzle box made of brass, that is slightly warm to the touch",
    "A cloudy chunk of glass that is said to hold a spark of breath from a blue dragon",
    "A crude chalice made of coal",
    "A miniature brass horn, silent when played, but fills the air with the scent of warm and exotic spices",
    "An eye-sized blue pearl that floats in salt water",
    "A tuning fork made from a dark metal which glows with a pale, white light during thunderstorms",
    "A small vial that is always filled with the smell of autumn wind",
    "A clear marble that slowly rolls toward the nearest source of running water",
    "A small collapsible silver cup that perspires constantly when opened",
    "An hourglass that tells time with falling mist instead of sand",
    "An ornate razor, which only cuts in freezing cold temperature",
    "A shark tooth covered in tiny etched words from a lost language",
    "A large brass coin with no markings or images on it",
    "A small wooden box filled with a strange red clay",
    "A necklace with a small, rusted iron anchor",
    "A small brass flute adorned with silver wire that is always faintly sounding",
    "A red and black Aarakocra feather",
    "A palm-sized stone with a hole in it, through which can be heard a constantly whispering wind",
    "A small conch shell covered in black crystal",
    "A small music box made of brass. It features a pair of tiny automatons that resemble Azer working at a forge",
    "A glass jar containing the preserved corpse of an unfamiliar aquatic creature",
    "A piece of petrified wood carved into the shape of a seashell",
    "A wooden puzzle cube covered in elemental symbols",
    "A small stone cube that acts as a magnet when placed against another stone",
    "A ring made of a white metal. On the inside is a name etched in Auran",
    "A bracelet made of silvered fish hooks",
    "A journal filled with poetry hand-written in Primordial",
    "A yellow gemstone that glows dimly when a storm is nearby",
    "A charred chisel with an unfamiliar symbol stamped into its base",
    "A canteen filled with a foul smelling orange mud",
    "A faceless doll made of driftwood",
    "A heavy iron key bearing the name of a ship long lost to the sea",
    "A small jewelry box made from the shell of a turtle",
    "A chess piece fashioned to look like fire myrmidon",
    "A spinning top with an image of one of the four elements on each side",
    "A single hoop earring made of a porous red stone",
    "An arrowhead carved from seasalt",
    "A small comb made of blue coral",
    "Seven small beads of sandstone on a string, all different colors",
    "A romance chapbook written in Undercommon titled 'Just one Layer of Grey'",
    "A tiny, broken clockwork Harpy",
    "An ivory whale statuette",
    "A fist-sized cog, covered in barnacles",
    "An eyepatch made of obsidian and a black leather cord",
    "	A glass bottle with a tiny ship of unfamiliar design inside",
    
    
    "A small notebook that causes anything written in it to disappear after 1 hour",
    "A crystal lens made of ivory and gold that causes anything observed through it to appear to be surrounded by motes of multicolored light",
    "A small golden pyramid inscribed with elven symbols and about the size of a walnut",
    "A cloak pin made from enamel in the shape of a butterfly; when you take the pin off, it turns into a real butterfly, and returns when you are ready to put your cloak back on again",
    "A golden compass that points toward the nearest portal to the Feywild within 10 miles",
    "A small silver spinning top that, when spun, endlessly spins until interrupted",
    "A small songbird made of enamel, gold wire, and precious stone; uttering the songbird's name in Elvish causes the trinket to emit that bird's birdsong",
    "A small enamel flower that, when put in one's hair, animates, tying back the wearer's hair with a living vine with flowers; plucking a single flower from this vine returns it to its inanimate form",
    
    
    "A handheld device containing a glowing green gem that darkens when no oxygen is present",
    "A foot-long, egg-shaped object made from stitched leather",
    "A black metal cylinder that dictates the history of an unknown plant or animal species when held",
    "A cylindrical jar containing a pickled crustacean of unknown origin",
    "A small thumb-button storage cylinder that releases a useless iron key when pressed",
    "An unusual heraldic cloak pin that emits a short musical fanfare when tapped",
    "A handheld tube that sucks in dust when squeezed and captures it in a detachable compartment",
    "A scintillating disk of unknown material",
    "A dial that can be twisted to slowly click back to its origin, whereupon it emits a loud ringing noise",
    "A hovering, apple-sized orb of metal that follows you around",
    "The petrified cocoon of an unknown insect",
    "A bronze gauntlet set with many slots, and which violently expels any object pressed into those slots",
    "A box that plays an illusory message in an unknown language when opened",
    "A rod that causes you to forget the last five minutes when you press a button near its tip",
    "A palm-sized cylinder that emits a harmless ray of glowing blue light when squeezed",
    "A bead that suppresses your hearing when secreted inside either ear, causing you to be deafened",
    "An amulet that displays your current health as a green bar above your head, with the bar retracting as your hit point total decreases",
    "A casket containing one hundred tasteless blue pills that produce no discernible effect when swallowed",
    "A metal mechanical puzzle with no apparent solution",
    "A metal spinning top that never tips over when spun",
    "Two strips of cloth-like material, each coated with a soft, hair-like fuzz on one side",
    "A simple wire pyramid that preserves any foodstuffs it is placed over",
    "A star chart labeled in an unknown script",
    "A rectangle of black glass that displays indecipherable arcane runes when you swipe your finger across it",
    "A schematic that shows the inner workings of an impossibly complex device",
    "An odd pair of comfortable shoes made from supple, multicolored material",
    "A mirror that makes you appear more beautiful when you tap your reflection",
    "A mechanical metal puppy that playfully follows you around when activated",
    "A talking bracelet that speaks only to correct your grammar",
    "A bar of soap that can remove any stain",
    "A journal in Common, written by someone in a world similar to but not quite the same as your own",
    "A tub containing one serving of disgusting but nutritious goop that refills itself slowly over the course of one week",
    "An instruction manual for activating a mysterious, world-destroying device",
    "A small supple disk that displays weird moving symbols when placed over either eye",
    "A tiny desk set with large, colorful buttons, each of which plays a discordant musical fanfare when pressed",
    "A pair of tinted spectacles that reduce the glare of the sun when worn",
    "An inflatable bedroll made from an unknown material, and which slowly deflates when used",
    "A rod tipped with a blunt metal pincer whose grip can be adjusted by turning a screw",
    "A battered helmet with a transparent orange visor that flips into place when donned",
    "An animated map of a mysterious city that appears to be tracking the movements of five creatures",
    "A cylinder of mist that holds your hair perfectly in shape when sprayed onto your head",
    "A talking wand that tells you the name of any plant you point it at",
    "A metal bracelet that displays the number of steps you've taken since your last long rest",
    "A tiny handheld device that projects a glowing dot onto whatever you point it at",
    "A rectangular piece of glass that displays a twelve-digit countdown on its surface",
    "A wall chart of mysterious formulae arranged into a color-coded grid",
    "A handheld device that solves any math problem you input using its buttons",
    "A ball of speckled brown fur that appears to be alive",
    "A complicated crystal board game that you don't know how to play",
    "A large glass rectangle that displays a storm of black and white patterns when you press a button on its underside",
    
    
    "A small wooden figurine of a yawning walrus, painted in red and black",
    "A pair of scrimshaw cufflinks with an image of a fisherman on a boat engraved on them",
    "A small iron key with a frayed blue and gold cord tied to it",
    "A small illustrated book of Northlander myths that has pages missing",
    "A damaged scrimshaw cameo depicting a merfolk",
    "A stone from a burial cairn with a tiny Dwarvish rune carved into it",
    "A ripped cloth sail with a symbol you don't recognize",
    "An Ulu knife with a scrimshaw handle",
    "A jar containing an unidentifiable, sweet, sticky substance",
    "A delicate glass ball painted with snowflakes, capped by a metal loop with a tiny hook attached to it",
    "An expedition log with missing pages and a pressed flower used as a bookmark",
    "An owl figurine carved from whalebone",
    "A sewing box that smells of old wood and has three spools of blue thread inside",
    "A scrimshaw-handled ink pen with black runic designs along its length",
    "A brooch made from a small insect encased in amber",
    "A scrimshaw pepper shaker etched with the letter W",
    "An old, wooden-handled ice pick stained with blood that won't wash off",
    "A fabric doll bearing an angry expression",
    "A set of wind chimes made from seashells",
    "A beautiful silver tin that, when opened, emits the smell of rotting fish",
    "A bloodstained dreamcatcher made from fishing line, gold wire, and snowy owlbear feathers",
    "A figurine of a polar bear made of ice that never melts",
    "A snow globe that doesn't need to be shaken",
    "A piece of sea glass shaped like a unicorn's horn",
    "A dark blue scarf that gets lighter in shade the higher the altitude of the wearer",
    
    
    "A small wooden figurine of a yawning walrus, painted in red and black",
    "A pair of scrimshaw cufflinks with an image of a fisherman on a boat engraved on them",
    "A small iron key with a frayed blue and gold cord tied to it",
    "A small illustrated book of Northlander myths that has pages missing",
    "A damaged scrimshaw cameo depicting a merfolk",
    "A stone from a burial cairn with a tiny Dwarvish rune carved into it",
    "A ripped cloth sail with a symbol you don't recognize",
    "An Ulu knife with a scrimshaw handle",
    "A jar containing an unidentifiable, sweet, sticky substance",
    "A delicate glass ball painted with snowflakes, capped by a metal loop with a tiny hook attached to it",
    "An expedition log with missing pages and a pressed flower used as a bookmark",
    "An owl figurine carved from whalebone",
    "A sewing box that smells of old wood and has three spools of blue thread inside",
    "A scrimshaw-handled ink pen with black runic designs along its length",
    "A brooch made from a small insect encased in amber",
    "A scrimshaw pepper shaker etched with the letter W",
    "An old, wooden-handled ice pick stained with blood that won't wash off",
    "A fabric doll bearing an angry expression",
    "A set of wind chimes made from seashells",
    "A beautiful silver tin that, when opened, emits the smell of rotting fish",
    "A bloodstained dreamcatcher made from fishing line, gold wire, and snowy owlbear feathers",
    "A figurine of a polar bear made of ice that never melts",
    "A snow globe that doesn't need to be shaken",
    "A piece of sea glass shaped like a unicorn's horn",
    "A dark blue scarf that gets lighter in shade the higher the altitude of the wearer",
    
    
    "A bronzewood ring inscribed with the Elvish word for 'hope'",
    "A dried flower; if it's placed in water, it blooms",
    "An ebony locket; when it's opened, an elven voice whispers 'Always'",
    "A tiny skull carved from dark wood",
    "A finger bone inscribed with an unknown sigil",
    "An ivory flute which produces no sound",
    "A small journal made from preserved leaves",
    "A book of poetry written by undead elves",
    
    "A pierced dragon scale on a cord",
    "A statuette of a dragon carved from black bone",
    "A dragon's tooth, engraved with an unknown sigil",
    "A child's doll of a dragon, woven from leather cords",
    "A dagger carved from a dragon's talon",
    "A brass disk bearing the silhouette of a black dragon",
    "A small egg-shaped piece of polished bone",
    "A bone fragment with brass inlaid runes",
    "A leather pouch filled with tiny draconic teeth",
    "A single large seed that's warm to the touch",
    "A pressed flower with vivid green petals; when you smell it, you hear eerie music",
    "A tiny ball of putty; if you set it down, it begins to slowly crawl around",
    "A perpetually warm disk of dark iron",
    "A small journal with leathery pages; any words you write in it slowly disappear",
    "A four-sided die carved with strange markings",
    "A cameo with the silhouette of an unknown species",
    "A preserved finger with purple flesh and four joints",
    "A perfectly preserved eye; if you set it down, it rotates to follow your movement",
    "A small box; when opened, you alone hear screaming",
    "A preserved insect; you've never seen another like it",
    "A polished crystal sphere; when you clutch it in your fist, a telepathic voice recites a story in your mind",
    "A teardrop pendant made from polished shell; when you hold it, you see the image of a young Riedran man",
    "A six-sided crystal die; when you roll it, you feel a surge of emotion for six seconds",
    "A sealed vial filled with faintly luminescent blue mist",
    "A crystal disk engraved with a labyrinthine pattern",
    "A leather-bound collection of kalashtar poetry called Shards of the Light",
    "A sphere of polished crystal; when you hold it in your palm, you feel that it knows you and understands you",
    "A cup and ball toy; when you successfully catch the ball in the cup, you feel a momentary surge of joy",
    "A punched ticket for a voyage from Sharn to Stormreach",
    "A scorpion's barb engraved with a single Elvish letter",
    "A copper coin so big you could use it as a dinner plate",
    "An image of an elf warrior engraved on a giant's tooth",
    "A single page from a giant wizard's spellbook, bearing an incomplete spell",
    "A scrap of parchment, part of a map of Stormreach",
    "A small book titled Feersome Beests of Zendrik",
    "A scrimshaw carving of a sahuagin",
    "A small prism carved from ice that doesn't melt",
    "A rusted iron coin, depicting a dwarf lord and the worlds 'Five Rex Undra'",
    "A pair of eight-sided dice carved from ice that doesn't melt",
    "A swatch of silvery fur that's cold to the touch, possibly from a winter wolf",
    "A snowball; it doesn't melt and can't be compressed into ice",
    "A tiny white dragon sculpted from ice that doesn't melt",
    "A key carved from ice that doesn't melt",
    "A single scale from a white dragon"
    ] 
function die(num){
    let roll = Math.floor(Math.random()*num)
    return roll
    }
function getTrinket (){
  return trinkets[die(trinkets.length)]
}
function displayTrinket() {
    document.getElementById("main-text").innerHTML = `${getTrinket()}`;
}